import { serve } from "https://deno.land/std@0.168.0/http/server.ts";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers":
    "authorization, x-client-info, apikey, content-type, x-supabase-client-platform, x-supabase-client-platform-version, x-supabase-client-runtime, x-supabase-client-runtime-version",
};

const GITHUB_API = "https://api.github.com";

serve(async (req) => {
  if (req.method === "OPTIONS") {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    const GITHUB_TOKEN = Deno.env.get("GITHUB_TOKEN");
    if (!GITHUB_TOKEN) throw new Error("GITHUB_TOKEN is not configured");

    const { action, payload } = await req.json();

    const ghFetch = async (path: string, method = "GET", body?: any) => {
      const resp = await fetch(`${GITHUB_API}${path}`, {
        method,
        headers: {
          Authorization: `token ${GITHUB_TOKEN}`,
          Accept: "application/vnd.github.v3+json",
          "Content-Type": "application/json",
          "User-Agent": "Architect-AI-Lab",
        },
        ...(body ? { body: JSON.stringify(body) } : {}),
      });
      const data = await resp.json();
      if (!resp.ok) throw new Error(`GitHub API error [${resp.status}]: ${JSON.stringify(data)}`);
      return data;
    };

    let result: any;

    switch (action) {
      case "create_repo": {
        const { name, description, isPrivate } = payload;
        result = await ghFetch("/user/repos", "POST", {
          name,
          description: description || `Created by Architect AI Lab`,
          private: isPrivate ?? true,
          auto_init: true,
        });
        break;
      }

      case "create_branch": {
        const { owner, repo, branch, from_branch } = payload;
        const ref = await ghFetch(`/repos/${owner}/${repo}/git/ref/heads/${from_branch || "main"}`);
        result = await ghFetch(`/repos/${owner}/${repo}/git/refs`, "POST", {
          ref: `refs/heads/${branch}`,
          sha: ref.object.sha,
        });
        break;
      }

      case "commit_files": {
        const { owner, repo, branch, files, message } = payload;
        // Get current commit SHA
        const ref = await ghFetch(`/repos/${owner}/${repo}/git/ref/heads/${branch}`);
        const commitSha = ref.object.sha;
        const commit = await ghFetch(`/repos/${owner}/${repo}/git/commits/${commitSha}`);
        const treeSha = commit.tree.sha;

        // Create blobs for each file
        const tree = [];
        for (const file of files) {
          const blob = await ghFetch(`/repos/${owner}/${repo}/git/blobs`, "POST", {
            content: file.content,
            encoding: "utf-8",
          });
          tree.push({
            path: file.path,
            mode: "100644",
            type: "blob",
            sha: blob.sha,
          });
        }

        // Create tree
        const newTree = await ghFetch(`/repos/${owner}/${repo}/git/trees`, "POST", {
          base_tree: treeSha,
          tree,
        });

        // Create commit
        const newCommit = await ghFetch(`/repos/${owner}/${repo}/git/commits`, "POST", {
          message: message || "Architect AI: automated commit",
          tree: newTree.sha,
          parents: [commitSha],
        });

        // Update ref
        result = await ghFetch(`/repos/${owner}/${repo}/git/refs/heads/${branch}`, "PATCH", {
          sha: newCommit.sha,
        });
        break;
      }

      case "create_pr": {
        const { owner, repo, title, body, head, base } = payload;
        result = await ghFetch(`/repos/${owner}/${repo}/pulls`, "POST", {
          title,
          body: body || "Auto-generated by Architect AI Lab",
          head,
          base: base || "main",
        });
        break;
      }

      case "list_repos": {
        result = await ghFetch("/user/repos?sort=updated&per_page=20");
        break;
      }

      default:
        throw new Error(`Unknown action: ${action}`);
    }

    return new Response(JSON.stringify({ success: true, data: result }), {
      headers: { ...corsHeaders, "Content-Type": "application/json" },
    });
  } catch (e) {
    console.error("github-engineer error:", e);
    return new Response(
      JSON.stringify({ success: false, error: e instanceof Error ? e.message : "Unknown error" }),
      { status: 500, headers: { ...corsHeaders, "Content-Type": "application/json" } }
    );
  }
});
